fix,solaris: "version" conflicts with math namespace
lib/Basics/RandomGenerator.cpp: In function 'arangodb::basics::Random::random_e arangodb::basics::Random::selectVersion(arangodb::basics::Random::random_e)':
lib/Basics/RandomGenerator.cpp:544:25: error: reference to 'version' is ambiguous
   random_e oldVersion = version;
                         ^
In file included from ./lib/Basics/Common.h:62:0,
                 from lib/Basics/RandomGenerator.h:27,
                 from lib/Basics/RandomGenerator.cpp:24:
/opt/local/gcc49/lib/gcc/x86_64-sun-solaris2.11/4.9.3/include-fixed/math.h:119:6: note: candidates are: enum version
 enum version {libm_ieee = -1, c_issue_4, ansi_1, strict_ansi};