Revert "Fix markdown build errors"
This reverts commit ae6b1e1e08562ef874d15d924261659489c7e710.
Exception: Changes to Arangosh/README.md, which is a local file.