on solaris, v8 gtest looks for the third type of char (?)
../testing/gtest/include/gtest/gtest_pred_impl.h: In instantiation of 'testing::AssertionResult testing::AssertPred2Helper(const char*, const char*, const char*, Pred, const T1&, const T2&) [with Pred = v8::base::bit_equal_to<char>; T1 = char; T2 = char]':
../test/unittests/base/functional-unittest.cc:113:5:   required from 'void v8::base::FunctionalTest_BitEqualTo_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = char]'
../test/unittests/base/functional-unittest.cc:196:1:   required from here
../testing/gtest/include/gtest/gtest_pred_impl.h:135:18: error: no match for call to '(v8::base::bit_equal_to<char>) (const char&, const char&)'
   if (pred(v1, v2)) return AssertionSuccess();